// Rotating example prompts shown as an animated placeholder in the AI planner
// input. They are inspiration only — never auto-submitted — so they showcase
// the planner's range (destinations across Trento/Rovereto, every mode).

export const AI_PROMPT_PRESETS: string[] = [
  'Portami alla stazione di Trento in autobus',
  'Voglio andare a Rovereto in treno',
  'Come arrivo al MART a piedi',
  'Taxi per l’ospedale Santa Chiara',
  'Andare in piazza Duomo a Trento',
  'Raggiungere il Castello del Buonconsiglio',
  'Vai al MUSE in autobus',
  'Portami all’università di Trento',
  'Come arrivo a Piazza Fiera',
  'Taxi per la stazione di Rovereto',
  'Andare a Mezzocorona in treno',
  'Portami in centro a Trento a piedi',
  'Percorso per l’autostazione di Trento',
  'Vai alla biblioteca comunale di Trento',
  'Come arrivo al Doss Trento',
  'Voglio andare ad Ala in treno',
  'Taxi per il centro di Rovereto',
  'Trova il parcheggio più vicino',
  'Alla stazione di Rovereto a piedi',
  'Andare a Calliano in treno',
  'Vai al MART di Rovereto in autobus',
  'Come arrivo all’ospedale di Trento',
  'Voglio andare in piazza Battisti',
  'Portami al teatro Zandonai di Rovereto',
  'A piedi fino al Duomo di Trento',
  'Come raggiungo Piazza Rosmini',
  'Voglio andare a Bolzano in treno',
  'Al campus universitario in autobus',
  'Andare al mercato di Trento',
  'Vai alla funivia di Sardagna',
  'Come arrivo a Mezzolombardo in treno',
  'Un car sharing per la stazione',
  'Portami al Palazzo delle Albere',
  'Indicazioni per Piazza Dante',
  'Allo stadio di Trento in autobus',
  'Al centro commerciale di Rovereto',
  'Voglio andare a Lavis in treno',
  'Taxi per il MART, subito',
  'Alla cattedrale di Trento a piedi',
  'Raggiungere la stazione delle corriere',
  'Vai a Piazza della Mostra',
  'All’ospedale Santa Chiara in autobus',
  'Voglio andare a Trento nord in auto',
  'Portami al parco di Trento',
  'Percorso per Corso Bettini a Rovereto',
  'Andare a San Martino a piedi',
  'Alla stazione di Trento in taxi',
  'Un autobus per il centro storico',
  'Portami in Piazza Vittoria a Rovereto',
  'Voglio un taxi adesso',
];
